region_to_tid_dict = {
    "alaska and the north": 130,
    "california": 116,
    "eastern-canada": 59,
    "florida": 44,
    "great-lakes": 49,
    "mid-atlantic": 83,
    "new-england": 48,
    "northwest": 113,
    "plains": 121,
    "rocky-mountains": 110,
    "southeast": 67,
    "southwest": 119,
    "texas": 66,
    "western-canada": 138,
    "north-america": -1,
}
